[Translation] [Indonesian]: /id/guide/introduction.md
CikiMomogi-grammY/website pull request #11
Opened 2022-05-21 22:01 UTC by CikiMomogi

To Do:
- [x] Translate
- [ ] Fix the anchor links

2022-05-27 23:05 UTC, sensen commented on site/docs/id/guide/introduction.md
> +grammY adalah _library_ atau _perpustakaan_ yang membuat penulisan bot yang sedemikian rupa menjadi sangat mudah.
```suggestion
grammY adalah _library_ atau _pustaka_ yang membuat penulisan bot menjadi sangat mudah.
```

2022-05-27 23:08 UTC, sensen commented on site/docs/id/guide/introduction.md
> +Kode program tersebutlah yang menentukan _apa yang harus dikerjakan oleh bot_, misalnya "ketika pengguna mengirim pesan ini, tanggapi dengan pesan itu", dan sebagainya.
```suggestion
Kode program menjelaskan _apa dikerjakan oleh bot_, misalnya "ketika pengguna mengirim pesan ini, tanggapi dengan pesan itu", dan sebagainya.
```

2022-06-20 04:22 UTC, sensen commented on site/docs/id/guide/introduction.md
> +> Kalau sudah tahu cara membuat bot, kunjungi subbab [Memulai](./getting-started.md)!
```suggestion
> Kalau sudah tahu cara membuat bot, kunjungi [Memulai](./getting-started.md)!
```

2022-06-20 04:22 UTC, sensen commented on site/docs/id/guide/introduction.md
> +> Kalau sudah tahu cara membuat bot, kunjungi subbab [Memulai](./getting-started.md)!
Lebih sederhana.

2022-06-20 04:22 UTC, sensen commented on site/docs/id/guide/introduction.md
> +> Lewati bagian ini jika kamu cuma ingin bermain-main dengan bot, langsung lompat ke bagian [Persiapan untuk Memulai](#persiapan-untuk-memulai).
```suggestion
> Lewati bagian ini jika kamu cuma ingin bermain-main dengan bot, langsung lompat ke [Persiapan untuk Memulai](#persiapan-untuk-memulai).
```

2022-06-20 04:22 UTC, sensen commented on site/docs/id/guide/introduction.md
> +> Lewati bagian ini jika kamu cuma ingin bermain-main dengan bot, langsung lompat ke bagian [Persiapan untuk Memulai](#persiapan-untuk-memulai).
Lebih sederhana.

2022-07-26 14:43 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +…kecuali, kalau kamu benar-benar serius dengan proyek bot kamu.
Itu sambungan dari baris ke-26. Gaya penulisannya di dokumen yang asli seperti itu. Jadi saya ikuti saja.

2022-07-26 14:43 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +1. Buat sorce file `bot.ts` menggunakan TypeScript, misalnya dengan menggunakan [VSCode](https://code.visualstudio.com/) (atau kode editor lainnya).
source!

2022-07-29 15:17 UTC, fadzikri requested changes
Wah ini review terlama yang pernah ku lakukan, sekitar 50 menit.

2022-07-29 15:17 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Meski kamu menulis kode menggunakan TypeScript, namun berbeda dengan Deno, Node.js tidak benar-benar menjalankan TypeScript.
Nah di paragraf ini aku agak susah bacanya, tapi bisa dipahami, coba di buat user-friendly lagi.

Kalau saran aku ya, dari `Meski ... dilakukan.` menjadi 👇🏻 

```
Menggunakan Deno membuat kamu menuliskan kode dengan menggunakan TypeScript. Tetapi pada Node.js sintaks tersebut tidak dapat dijalankan alih-alih mengompilasinya menjadi sintaks Javascript.  

Agar file TypeScript dapat dijalankan pada Node.js, perlu untuk dikompilasi terlebih dahulu yang nantinya akan menghasilkan file Javascript. (misalnya dari file `bot.ts`, setelah dikompilasi akan menjadi `bot.js`.)

Baris perintah untuk melakukan proses kompilasi tersebut, nantinya akan dibahas pada materi selanjutnya ketika kamu sudah selesai membuat bot. Yang penting, kamu sudah tahu langkah-langkah tersebut.
```

Yah, itu saja sih. Aku agak ngantuk mikir ini :D

2022-07-29 15:18 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Bot sudah beres dibuat…
Tapi dibagian bawah setelah ini, agak kurang nyambung.

2022-07-29 15:22 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Meski kamu menulis kode menggunakan TypeScript, namun berbeda dengan Deno, Node.js tidak benar-benar menjalankan TypeScript.
Yah ada pengulangan sih di saranku pada kalimat kedua, padahal dikalimat pertama sudah dijelasin juga.

2022-07-29 16:13 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +Baris perintah persisnya untuk proses di atas akan dibahas di materi selanjutnya ketika kamu selesai membuat botnya. Intinya, penting untuk diketahui bahwa tahap-tahap tadi perlu dilakukan.
Gini?
```suggestion
Berbeda dengan Deno, TypeScript di Node.js tidak bisa dijalankan secara langsung.
File TypeScript perlu di-compile terlebih dahulu supaya menghasilkan file JavaScript (misalnya dari file `bot.ts`, setelah dikompilasi akan menjadi `bot.js`).
Nah, file JavaScript inilah yang akan dijalankan oleh Node.js.

Baris perintah untuk melakukan proses kompilasi tersebut, akan dibahas pada materi selanjutnya ketika kamu sudah selesai membuat bot.
Yang penting, kamu sekarang sudah tahu kalau TypeScript di Node.js perlu di-compile terlebih dahulu agar bisa digunakan.
```

2022-07-29 16:13 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +Tekan `Ctrl+C` di terminal untuk menghentikan proses, yang juga akan menghentikan bot kamu.
Sip.

2022-07-29 16:15 UTC, CikiMomogi commented
Wait.. what? LOL. 
I didn't mean to do that.

2022-07-29 16:17 UTC, CikiMomogi commented
Lesson learned. Press the `commit suggestion` button instead of `review` button :P

2022-07-30 00:04 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Source code menjelaskan _apa dikerjakan oleh bot_, misalnya "Ketika pengguna mengirim pesan ini, tanggapi dengan pesan itu", dan sebagainya.
Hmm ...bolehlah.

2022-07-30 00:05 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Bot sudah beres dibuat…
oh ok.

2022-07-30 00:08 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Selain itu, ada berbagai hal lain yang dilakukan grammY untuk mempermudah pembuatan bot.
Oh iya ya, jadinya hanya seperti dapat mampu saja, seperti belum dibuat hal lainnya.

2022-07-30 00:09 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +(Jika menjumpai orang-orang menyebutnya _Node_, mereka terlalu malas untuk menambahkan imbuhan ".js", tetapi maksudnya sama saja.)
Ok, bisalah.

2022-07-30 00:12 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Jika perlu terhubung ke database yang tidak umum digunakan atau melakukan hal-hal lain yang berhubungan dengan _low-level system_, sangat besar kemungkinannya semua itu bisa dikerjakan dengan Node.js
Ok, bisa dibaca dengan user-friendly.

Tapi, kayaknya bagian `dan sudah lama dikembangkan. Karena ia sudah lama dikembangkan, maka tidak heran` Jadi berasa dua kali diulang? Kalau dibuat `dan sudah lama dikembangkan. Karena itu, maka tidak heran .....`.

2022-07-30 00:19 UTC, fadzikri commented
> Wait.. what? LOL. I didn't mean to do that.

Bruh, i was confused. Why are you reviewing yourself and answering by yourself too. 😅

2022-07-30 13:49 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +Jika perlu terhubung ke database yang tidak umum digunakan atau melakukan hal-hal lain yang berhubungan dengan _low-level system_, sangat besar kemungkinannya semua itu bisa dikerjakan dengan Node.js
Ok

2022-07-30 14:02 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Baris perintah persisnya untuk proses di atas akan dibahas di materi selanjutnya ketika kamu selesai membuat botnya. Intinya, penting untuk diketahui bahwa tahap-tahap tadi perlu dilakukan.
Yoii, bisalah ...

2022-07-30 14:48 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Sebelum mulai membuat bot, ketahui terlebih dahulu apa yang dapat dan tidak dapat dilakukan oleh bot Telegram.
```suggestion
Sebelum memulai untuk membuat bot, ketahui terlebih dahulu apa yang dapat dan tidak dapat dilakukan oleh bot Telegram.
```

2022-07-31 04:05 UTC, fadzikri requested changes

2022-07-31 04:05 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +- Tidak ada file `package.json` untuk dikonfigurasi,
```suggestion
- Tidak ada file `package.json` untuk dikonfigurasi.
```

2022-07-31 04:05 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +- Tidak ada `node_modules` untuk diurusi,
```suggestion
- Tidak ada `node_modules` untuk diurusi.
```

2022-07-31 04:05 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +- Unggul, memiliki _development tools_ bawaan,
```suggestion
- Unggul, memiliki _development tools_ bawaan.
```

2022-07-31 04:05 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +- Sistem keamanan yang jauh lebih baik,
```suggestion
- Sistem keamanan yang jauh lebih baik.
```

2022-07-31 04:05 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +- Tidak ada file `package.json` untuk dikonfigurasi,
Bagian ini titik kah? atau memang koma?

2022-07-31 05:27 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +Sebelum mulai membuat bot, ketahui terlebih dahulu apa yang dapat dan tidak dapat dilakukan oleh bot Telegram.
Kayaknya kalau ditambah `untuk` malah tidak efisien. Tapi untuk penambahan `kamu harus tahu` aku setuju. Jadinya nanti kayak gini `Sebelum mulai membuat bot, kamu harus paham apa yang dapat dan tidak dapat dilakukan oleh bot Telegram.`?

2022-07-31 05:28 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +- Tidak ada file `package.json` untuk dikonfigurasi,
Harusnya pakai titik koma (;) malah kalau ikut aturan KBBI. Nanti kita benerin semua pas review ulang.

2022-07-31 05:32 UTC, CikiMomogi commented on site/docs/id/guide/introduction.md
> +- Tidak ada file `package.json` untuk dikonfigurasi,
Aku edit aja jadi kalimat lengkap.

2022-07-31 07:30 UTC, fadzikri commented on site/docs/id/guide/introduction.md
> +Sebelum mulai membuat bot, ketahui terlebih dahulu apa yang dapat dan tidak dapat dilakukan oleh bot Telegram.
Boleh-boleh

2022-07-31 07:47 UTC, fadzikri commented
Ini gimana nanti approve-nya? di bagian `Files Changed` ada 5 file disitu. Takutnya, nanti ke approve semua.

2022-07-31 07:54 UTC, CikiMomogi commented
Tidak apa-apa aku commit manual saja.

2022-08-01 02:17 UTC, CikiMomogi commented
> What should i review?

Review the latest changes, https://github.com/CikiMomogi-grammY/website/pull/11/commits/12162a778fa32bb5e45e817c075bfe44c622a5e6

2022-08-01 12:25 UTC, fadzikri commented
Approve-nya gimana? apa langsung approve disini?

2022-08-01 13:08 UTC, CikiMomogi commented
Yes

2022-08-01 13:29 UTC, fadzikri approved these changes
Good work ...

2022-08-19 03:57 UTC, merged