[Translation] [Indonesian]: /id/guide/api.md
CikiMomogi-grammY/website pull request #15
Opened 2022-05-25 03:24 UTC by CikiMomogi

2022-05-27 22:38 UTC, sensen commented on site/docs/id/guide/api.md
> +Karenanya, untuk menyiasati batasan tersebut, daripada menggunakan server API Bot milik Telegram, kamu bisa [menghosting server API Bot-mu sendiri](https://core.telegram.org/bots/api#using-a-local-bo
This might be more concise without losing the meaning.

Untuk menyiasati batasan tersebut, kamu bisa [menghosting server API Bot-mu sendiri](https://core.telegram.org/bots/api#using-a-local-bot-api-server) supaya bot kamu bisa mengirim berkas dengan ukuran hingga 2000 MB.

2022-05-27 22:40 UTC, sensen commented on site/docs/id/guide/api.md
> +## Memanggil Api Bot
Maybe `API`?

2022-05-27 22:44 UTC, KnorpelSenf commented on site/docs/id/guide/api.md
> +Karenanya, untuk menyiasati batasan tersebut, daripada menggunakan server API Bot milik Telegram, kamu bisa [menghosting server API Bot-mu sendiri](https://core.telegram.org/bots/api#using-a-local-bo
You can directly make suggestions inline on GitHub with the button above the text field:
```suggestion
Untuk menyiasati batasan tersebut, kamu bisa menghosting server API Bot-mu sendiri supaya bot kamu bisa mengirim berkas dengan ukuran hingga 2000 MB.
```

2022-05-27 22:48 UTC, sensen commented on site/docs/id/guide/api.md
> +Karenanya, untuk menyiasati batasan tersebut, daripada menggunakan server API Bot milik Telegram, kamu bisa [menghosting server API Bot-mu sendiri](https://core.telegram.org/bots/api#using-a-local-bo
Didn't realize this! Thank you!

2022-05-27 22:48 UTC, sensen commented on site/docs/id/guide/api.md
> +## Memanggil Api Bot
```suggestion
## Memanggil API Bot
```

2022-05-27 22:51 UTC, sensen commented on site/docs/id/guide/api.md
> +Sebagai contoh, sebelum dikirim, beberapa properti dalam method-method tertentu harus melalui proses perangkaian JSON atau `JSON.stringify` terlebih dahulu .
```suggestion
Sebagai contoh, beberapa properti dalam method-method tertentu harus melalui proses `JSON.stringify` terlebih dahulu sebelum dikirim.
```

2022-08-02 05:05 UTC, fadzikri requested changes

2022-08-02 05:06 UTC, fadzikri approved these changes
Ok, good.

2022-08-02 05:14 UTC, CikiMomogi commented on site/docs/id/guide/api.md
> +API Bot Telegram adalah salah satu bentuk spesifikasi dari interface tersebut. Isinya adalah sebuah [daftar panjang](https://core.telegram.org/bots/api) dari berbagai method dan data type, yang biasa
Nice.

2022-08-19 03:58 UTC, merged