[Transalation [Indonesian]: /id/guide/filter-queries.md
CikiMomogi-grammY/website pull request #16
Opened 2022-05-26 03:59 UTC by CikiMomogi

Ready to review.

Phew, this one took me a while to work on. The Query Language section was enough to rack my brain. There are a lot of technical terms that I have never heard of. However, I am pretty satisfied with the result.

2022-06-20 04:18 UTC, sensen reviewed
Ketemu 2 typo ini aja.

2022-06-20 04:18 UTC, sensen commented on site/docs/id/guide/filter-queries.md
> +Mengosongkan value _pertama_ akan menyocokkan pesan serta postingan channel.
```suggestion
Mengosongkan value _pertama_ akan mencocokkan pesan serta postingan channel.
```

2022-06-20 04:18 UTC, sensen commented on site/docs/id/guide/filter-queries.md
> +Mengosongkan value _kedua_ akan menyocokkan entity, baik di pesan maupun di caption.
```suggestion
Mengosongkan value _kedua_ akan mencocokkan entity, baik di pesan maupun di caption.
```

2022-06-20 23:34 UTC, sensen commented
Haha.. Thank you! I feel so special! 

On Mon, Jun 20, 2022, at 23:11, Ciki Momogi wrote:
> 
> 
> @sensen <https://github.com/sensen> just a little reminder, you can use the approved button to mark it as reviewed. I made it available exclusively for you, even @KnorpelSenf <https://github.com/KnorpelSenf> is not permitted to use it. 😛
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/CikiMomogi/website/pull/16#issuecomment-1160629632>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABQC24KPYUEBKMIX6VUOAT3VQCJ3TANCNFSM5W7P4APQ>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>

2022-08-04 04:46 UTC, fadzikri requested changes
Typo

2022-08-04 04:46 UTC, fadzikri commented on site/docs/id/guide/filter-queries.md
> +### Mengombinasikan Query sengan Method Lain
```suggestion
### Mengombinasikan Query dengan Method Lain
```

2022-08-04 04:50 UTC, fadzikri commented
> Phew, this one took me a while to work on. The Query Language section was enough to rack my brain. There are a lot of technical terms that I have never heard of. However, It may still be able to be improved, especially the Query Language section.

Yeah that's great one work, i can read that documentation easily and the terms are friendly enough to understand.

2022-08-05 07:57 UTC, fadzikri approved these changes
Ok, good ...

2022-08-19 04:04 UTC, merged