[Translation] [Indonesian]: /id/guide/middleware.md
CikiMomogi-grammY/website pull request #18
Opened 2022-05-27 03:45 UTC by CikiMomogi

Ready to review

2022-08-06 12:22 UTC, fadzikri requested changes
Check this...

2022-08-06 12:22 UTC, fadzikri commented on site/docs/id/guide/middleware.md
> +> Kalau kamu mencari dokumentasi khusus mengenai keiistimewaan middleware buatan grammY, silahkan baca materi [Membangkitkan Middleware](../advanced/middleware.md) di bab Tingkat Lanjut.
```suggestion
> Kalau kamu mencari dokumentasi khusus mengenai keistimewaan middleware buatan grammY, silahkan baca materi [Membangkitkan Middleware](../advanced/middleware.md) di bab Tingkat Lanjut.
```

2022-08-06 12:22 UTC, fadzikri commented on site/docs/id/guide/middleware.md
> +Ketika sebuah update berisi pesan teks biasa tiba, tindakan-tindakan berikut akan dilakukan:
```suggestion
Ketika sebuah update yang berisi pesan teks biasa tiba, tindakan-tindakan berikut akan dilakukan:
```

2022-08-06 12:22 UTC, fadzikri commented on site/docs/id/guide/middleware.md
> +  const before = Date.now(); // Milidetik
```suggestion
  const awal = Date.now(); // Milidetik
```

2022-08-06 12:22 UTC, fadzikri commented on site/docs/id/guide/middleware.md
> +  const after = Date.now(); // Milidetik
```suggestion
  const akhir = Date.now(); // Milidetik
```

2022-08-06 12:22 UTC, fadzikri commented on site/docs/id/guide/middleware.md
> +- :skull: Terkadang, juga dapat membunuh kucing imut yang tidak berdosa. :crying_cat_face:
> :skull: Terkadang, juga dapat membunuh kucing imut yang tidak berdosa. :crying_cat_face:

😮  .... 🤐   .... 🥺

2022-08-06 13:40 UTC, CikiMomogi commented on site/docs/id/guide/middleware.md
> +- :skull: Terkadang, juga dapat membunuh kucing imut yang tidak berdosa. :crying_cat_face:
:crying_cat_face:

2022-08-06 13:42 UTC, CikiMomogi commented
Naise!

2022-08-07 13:13 UTC, fadzikri approved these changes

2022-08-19 04:08 UTC, merged