[Translation] [Indonesian]: /id/guide/games.md
CikiMomogi-grammY/website pull request #22
Opened 2022-05-31 02:07 UTC by CikiMomogi

To do:
- [ ] Fix the anchor link

2022-05-31 02:11 UTC, CikiMomogi commented on site/docs/id/guide/games.md
> +Kamu juga bisa mengatur [inline keyboard](../plugins/keyboard.md#inline-keyboard) untuk menampilkan tombol khusus di pesan game tersebut.
- [ ] Fix this anchor link

2022-08-09 03:11 UTC, fadzikri requested changes
Improvitation?

2022-08-09 03:11 UTC, fadzikri commented on site/docs/id/guide/games.md
> +### Hasil Akhir Kode Kita Akan Terlihat Seperti Ini
```suggestion
### Hasil Akhir Kode Kita akan Terlihat seperti Ini
```

2022-08-09 03:11 UTC, fadzikri commented on site/docs/id/guide/games.md
> +Di masa mendatang, kami mungkin akan melanjutkan artikel ini di materi tingkat lanjut dan FAQ, meski begitu kami rasa materi ini sudah cukup untuk kamu bisa menjalankan game di Telegram.
```suggestion
Di masa mendatang, kami mungkin akan melanjutkan artikel ini di materi tingkat lanjut dan FAQ, meski begitu kami rasa materi ini sudah cukup untuk dapat menjalankan game-mu di Telegram.
```

2022-08-09 15:08 UTC, CikiMomogi commented on site/docs/id/guide/games.md
> +### Hasil Akhir Kode Kita Akan Terlihat Seperti Ini
The word `Akan` based on [KBBI](https://kbbi.kemdikbud.go.id/entri/akan) is not a particle, so it should be capitalized.

2022-08-19 04:11 UTC, merged