[Translation] [Indonesian]: /id/resources/comparison.md
CikiMomogi-grammY/website pull request #57
Opened 2022-07-28 06:25 UTC by CikiMomogi

Ready for review.

2022-07-28 07:05 UTC, fadzikri requested changes
Coba cek ini

2022-07-28 07:05 UTC, fadzikri commented on site/docs/id/resources/comparison.md
> +Ide untuk mengumpulkan semua kode di dalam satu file besar dan menggunakan sebuah object primitive `EventEmitter` untuk memproses stream suatu object yang kompleks (misalnya request web) adalah ide y
Aku belum paham di bagian ini, maksudnya apa `Ide untuk .... web)`. Tapi kalau dibagian `ide yang buruk ... lainnya.` itu bisa paham.

2022-07-28 07:05 UTC, fadzikri commented on site/docs/id/resources/comparison.md
> +   PTB—framework bot terbesar untuk Python—[mengumumkan sedang melakukan migrasi](https://t.me/pythontelegrambotchannel/94) ke pemrograman asynchronous pada bulan Januari 2021, yang diharapkan rampun
Apa perlu tambahan `akan`?

2022-07-28 07:08 UTC, fadzikri commented
![gambar](https://user-images.githubusercontent.com/109416385/181442625-d93af5cf-ff78-44ed-b3b5-b2daf4e2f6e3.png)

Bagian yang kekurangan itu, apa perasaanku terlalu panjang paragrafnya?

Kalau misalnya pada bagian `Bot selalu` dibuat jadi paragraf baru bagaimana?

2022-07-28 07:37 UTC, fadzikri commented on site/docs/id/resources/comparison.md
> +- Berjalan di Node.js, tetapi juga bisa berjalan di Deno dan di browser
Anggap saja seperti `di(Deno + browser)` , sehingga mirip `di Deno dan di browser` 😅

2022-07-28 10:37 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +## Saya Tidak Setuju Dengan Perbandingan Ini
Correct!

2022-07-28 10:47 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +Kekurangannya, ini dapat digunakan dengan baik untuk jangka pendek saja.
`Kekurangannya, framework semacam ini tidak dapat digunakan untuk jangka waktu yang lama.`?

2022-07-28 10:52 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +Ide untuk mengumpulkan semua kode di dalam satu file besar dan menggunakan sebuah object primitive `EventEmitter` untuk memproses stream suatu object yang kompleks (misalnya request web) adalah ide y
Kurang lebih kayak "Penerapan A dan B bukanlah ide yang bagus". Aku belum kepikiran kata hubung yang pas jadi ngikutin teks aslinya.

2022-07-28 10:53 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +Ide untuk mengumpulkan semua kode di dalam satu file besar dan menggunakan sebuah object primitive `EventEmitter` untuk memproses stream suatu object yang kompleks (misalnya request web) adalah ide y
`Ide untuk ...` di awal kalimat mending dihapus aja soalnya sudah disambung di bawahnya.

2022-07-28 10:59 UTC, CikiMomogi commented
> Kalau misalnya pada bagian `Bot selalu` dibuat jadi paragraf baru bagaimana?

Boleh.. boleh. Biar kelihatan rapi sedikit,

2022-07-28 11:00 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +# Bagaimana grammY Jika Dibandingkan dengan Framework Bot Lainnya
Iyes. Pakai tanda tanya

2022-07-28 11:59 UTC, fadzikri commented on site/docs/id/resources/comparison.md
> +Kekurangannya, ini dapat digunakan dengan baik untuk jangka pendek saja.
Kalau `semacam`, berarti yang lain ada yang mirip dengan ini dong?

2022-07-28 12:39 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +Kekurangannya, ini dapat digunakan dengan baik untuk jangka pendek saja.
Iya. Konteksnya kan ada dua macam framework: yang simpel (kayak NTBA) dan yang kompleks (kayak grammY), ada banyak lagi di luar sana framework simpel yang serupa dengan NTBA.

2022-07-28 12:58 UTC, fadzikri commented on site/docs/id/resources/comparison.md
> +Kekurangannya, ini dapat digunakan dengan baik untuk jangka pendek saja.
Oh oke.

2022-07-28 13:02 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +   PTB—framework bot terbesar untuk Python—[mengumumkan sedang melakukan migrasi](https://t.me/pythontelegrambotchannel/94) ke pemrograman asynchronous pada bulan Januari 2021, yang diharapkan rampun
Boleh

2022-07-28 13:25 UTC, fadzikri commented on site/docs/id/resources/comparison.md
> +Ide untuk mengumpulkan semua kode di dalam satu file besar dan menggunakan sebuah object primitive `EventEmitter` untuk memproses stream suatu object yang kompleks (misalnya request web) adalah ide y
Dari mana? apa dari `Ide untuk ... lainnya`?

2022-07-30 14:51 UTC, CikiMomogi commented on site/docs/id/resources/comparison.md
> +Ide untuk mengumpulkan semua kode di dalam satu file besar dan menggunakan sebuah object primitive `EventEmitter` untuk memproses stream suatu object yang kompleks (misalnya request web) adalah ide y
`Ide untuk mengumpulkan .... adalah ide yang buruk di dunia Telegram, selain itu ...`
Tapi biarin saja deh, kayaknya sudah pas.

2022-07-31 03:59 UTC, fadzikri approved these changes
Okelah bisa ....

2022-08-19 05:35 UTC, merged