[Translation] [Indonesian]: /id/hosting/deno-deploy.md
CikiMomogi-grammY/website pull request #60
Opened 2022-07-29 06:39 UTC by CikiMomogi

Work in progress.

2022-07-29 09:06 UTC, fadzikri commented
Jadi ini cara mengeditnya dari mana? dari repo manual kah? atau disini?

2022-07-29 10:15 UTC, fadzikri commented
Oh man, i didn't realize that.

2022-07-29 13:52 UTC, CikiMomogi commented
@fadzikri You can remove the tag when you are done with the translation.

2022-07-29 14:06 UTC, fadzikri commented
Ready to review

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +3. Kunjungi [dasbor Deno Deploy](https://dash.deno.com/projects).
```suggestion
3. Kunjungi [dashboard Deno Deploy](https://dash.deno.com/projects).
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +4. Pilih "New Project, dan pergi ke bagian "Deploy from GitHub repository".
```suggestion
4. Pilih "New Project", lalu pergi ke bagian "Deploy from GitHub repository".
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +5. Pasangkan aplikasi Github pada akunmu atau organisasimu, dah pilih repositorimu—yang terdapat kode bot.
```suggestion
5. Padang aplikasi Github di akun atau organisasimu, kemudian pilih repositori kode bot kamu berada.
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +6. Pilihlah branch yang stabil, dan kemudian pilih file `mod.ts` yang akan di deploy.
```suggestion
6. Pilih branch dan file `mod.ts` yang akan di-deploy.
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +> Metode ini diperuntukkan kepada pengguna tingkat lanjut yang nantinya projek akan di deploy melalui command line atau Github Actions.
```suggestion
> Metode ini diperuntukkan kepada pengguna tingkat lanjut yang nantinya proyek akan di-deploy melalui command line atau GitHub Actions.
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +1. Kunjungi [dasbor Deno Deploy](https://dash.deno.com/projects).
```suggestion
1. Kunjungi [dashboard Deno Deploy](https://dash.deno.com/projects).
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +3. Pasangkan [`deployctl`](https://github.com/denoland/deployctl).
```suggestion
3. Pasang [`deployctl`](https://github.com/denoland/deployctl).
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +4. Buatlah [access token](https://dash.deno.com/user/access-tokens).
```suggestion
4. Buat [token akses](https://dash.deno.com/user/access-tokens) baru.
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +> Semua yang kamu perlukan untuk mengikuti metode deploy ini adalah dengan menggunakan URL publik pada file `mod.ts`-mu.
```suggestion
> Kamu memerlukan URL publik yang mengarah ke file `mod.ts`-mu untuk menggunakan metode ini.
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +1. Buat projek baru pada Deno Deploy.
```suggestion
1. Buat proyek baru di Deno Deploy.
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +3. Masukkan URL publik pada file `mod.ts`-mu dan pilih "Deploy".
```suggestion
3. Masukkan URL publik file `mod.ts`-mu, lalu pilih "Deploy".
```

2022-07-29 15:22 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +ganti `<token>` dengan token bot-mu, dan `<url>` dengan URL lengkap pada aplikasimu.
```suggestion
Ganti `<token>` dengan token bot-mu, dan `<url>` dengan URL lengkap pada aplikasimu.
```

2022-07-29 15:23 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +Panduan ini akan memberitahukanmu tentang cara agar dapat meng-hosting bot pada [Deno Deploy](https://deno.com/deploy).
Nah ini, dari awal aku udah bingung, rasanya kurang enak dibaca kalau pakai `Panduan ini` tapi gak kepikiran mau nulis apa.

2022-07-29 15:24 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +Panduan ini akan memberitahukanmu tentang cara agar dapat meng-hosting bot pada [Deno Deploy](https://deno.com/deploy).
Di apainkah? di commit?

2022-07-29 15:26 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +Deno Deploy mirip seperti platform serverless lainnya, tetapi hanya didedikasikan pada aplikasi Deno saja.
Aku kadang bimbang sih sama penggunaanya `pada`, `untuk` dan `di`, soalnya kalau sering nulis selalu asal pakai 3 kata itu kalau untuk masalah tempat/rujukan.

2022-07-29 15:27 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +> Ingat! bahwa kamu perlu [menjalankan bot dalam webhooks](../guide/deployment-types.md#bagaimana-cara-menggunakan-webhook), jadi seharusnya kamu menggunakan `webhookCallback` alih-alih memanggil `bo
Hmm ... ok, banyak juga ya, malahan dapat pesan 19 Hidden Coversation.

2022-07-29 15:28 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +1. Pastikan bahwa kamu punya file yang dapat melakukan exports pada object bot-mu, sehingga kamu dapat melakukan import ketika ingin menjalankannya.
Nah ini aku kurang paham maksudnya.

2022-07-29 15:30 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +2. Buatlah file yang bernama `mod.ts` atau `mod.js` ataupun terserah namanya sesuai dengan keinginanmu (tetapi kamu harus mengingatnya, karena nanti file tersebut akan digunakan sebagai file deploy u
Yah aku selalu kebiasaan kalau nulis kata hubung atau kata per-contoh-an sebelumnya selalu pakai `,`.

2022-07-29 15:30 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +    return new Response("Hello world!");
Aduh, sampai dibaca juga dong kodenya.

2022-07-29 15:31 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +Kami anjurkan agar kamu memiliki handler pada lokasi—direktori—rahasia daripada menempatkanya pada root (`/`).
Nah ini asli aku bingung, tapi aku paham kalau tokennya dalam path tertentu.

2022-07-29 15:33 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +Pada bagian ini nantinya kita akan menggunakan token bot (`/<bot token>`).
Sama, bagian ini aku kurang paham.

2022-07-29 15:34 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +## Deploying
Ini aku kepikiran mau nulis `Melakukan Deploy` tapi kepikiran sama judul paling atas yaitu `Hosting`, jadinya dari pada dibuat juga `Melakukan Hosting`, aku ikutin saja kalau untuk judul.

2022-07-29 15:35 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +> Keuntungannya yaitu Deno Deploy akan selalu melihat perubahan pada repositori yang didalamnya terdapat kode bot-mu, dan nanti akan di deploy secara otomatis ke versi yang baru—apabila terjadi perub
Nice ...

2022-07-29 15:35 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +1. Buatlah repositori pada Github, bisa dalam bentuk pribadi ataupun publik.
Lagi-lagi `pada` , `di`.

2022-07-29 15:37 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +3. Kunjungi [dasbor Deno Deploy](https://dash.deno.com/projects).
Yah, aku terlalu buat baku sih, padahal sudah baca panduan kalau hal-hal teknis tidak perlu diterjemah.

2022-07-29 15:38 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +5. Pasangkan aplikasi Github pada akunmu atau organisasimu, dah pilih repositorimu—yang terdapat kode bot.
`Pasang`?

2022-07-29 15:39 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +> Metode ini diperuntukkan kepada pengguna tingkat lanjut yang nantinya projek akan di deploy melalui command line atau Github Actions.
Hmm.. GitHub

2022-07-29 15:40 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +> Semua yang kamu perlukan untuk mengikuti metode deploy ini adalah dengan menggunakan URL publik pada file `mod.ts`-mu.
Hmmm ... oke.

2022-07-29 15:41 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +1. Buat projek baru pada Deno Deploy.
Lagi-lagi ~mie demi hemat~ `di`, `pada`.

2022-07-29 15:43 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +ganti `<token>` dengan token bot-mu, dan `<url>` dengan URL lengkap pada aplikasimu.
Yah, pada tulisan resminya memang kecil sih, aku ikutin saja.

2022-07-29 15:44 UTC, fadzikri commented
Terima kasih atas review pertamanya dari terjemahan pertamaku. 😃

2022-07-29 16:28 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +5. Pasangkan aplikasi Github pada akunmu atau organisasimu, dah pilih repositorimu—yang terdapat kode bot.
Kelihatan pas ngoreksi lagi laper nih wkwk

2022-07-29 16:30 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +ganti `<token>` dengan token bot-mu, dan `<url>` dengan URL lengkap pada aplikasimu.
Kalau ini preferensi pribadi sih. Ane ngelihatnya lebih pas kalau pakai kapital. Tapi, secara tata bahasa seharusnya memang kecil karena nyambung di baris atasnya. Gimana menurut kamu?

2022-07-29 16:31 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +> Semua yang kamu perlukan untuk mengikuti metode deploy ini adalah dengan menggunakan URL publik pada file `mod.ts`-mu.
Ada yang kurang pas?

2022-07-29 16:37 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +## Deploying
`Melakukan Deploy` juga bisa. Kalau `Hosting` aku gak nemu kata lain yang sesuai, jadi ngikut istilah teknisnya saja. Toh, aku yakin sudah banyak yg paham dengan istilah hosting.

2022-07-29 16:40 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +Pada bagian ini nantinya kita akan menggunakan token bot (`/<bot token>`).
Misal token bot kamu `abcdef:123456`, nanti url lengkapnya jadi `https://example.com/abcdef:123456`. Ga ada yang bisa nebak url random tersebut, karena token bot cuma kita yang tahu. Kalau sampai ketebak bisa-bisa di-spam nanti.

2022-07-29 16:41 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +Kami anjurkan agar kamu memiliki handler pada lokasi—direktori—rahasia daripada menempatkanya pada root (`/`).
Relatable. Nyusun kata-katanya ya yang susah. Itu yang bikin nge-translate jadi lama. Mikir kalimat yang pas wkwk

2022-07-29 16:42 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +    return new Response("Hello world!");
Yaya dong, Totalitas!

2022-07-29 16:47 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +Panduan ini akan memberitahukanmu tentang cara agar dapat meng-hosting bot pada [Deno Deploy](https://deno.com/deploy).
Ke tab `Files Changed` dulu, terus pilih `Add suggestion to batch`.

2022-07-30 00:22 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +Pada bagian ini nantinya kita akan menggunakan token bot (`/<bot token>`).
Lah jadi webhooks dong.

2022-07-30 00:23 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +## Deploying
Itu aja juga gak apa sih.

2022-07-30 00:25 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +> Semua yang kamu perlukan untuk mengikuti metode deploy ini adalah dengan menggunakan URL publik pada file `mod.ts`-mu.
> Ada yang kurang pas?

Oh udah pas, itu cuman kebiasaan ku selalu hmm... diawal kata 😅 .

2022-07-30 00:26 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +ganti `<token>` dengan token bot-mu, dan `<url>` dengan URL lengkap pada aplikasimu.
Buat aja kapital biar rapi.

2022-07-31 04:15 UTC, fadzikri requested changes

2022-07-31 04:15 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +5. Pasang aplikasi Github di akun atau organisasimu, kemudian pilih repositori kode bot kamu berada.
```suggestion
5. Pasang aplikasi GitHub di akun atau organisasimu, kemudian pilih repositori tempat kode bot kamu berada.
```

2022-07-31 04:15 UTC, fadzikri commented on site/docs/id/hosting/deno-deploy.md
> +6. Persiapan menggunakan Github Actions, dapat merujuk ke [sini](https://github.com/denoland/deployctl/blob/main/action/README.md).
```suggestion
6. Persiapan menggunakan GitHub Actions, dapat merujuk ke [sini](https://github.com/denoland/deployctl/blob/main/action/README.md).
```

2022-07-31 05:40 UTC, CikiMomogi commented on site/docs/id/hosting/deno-deploy.md
> +5. Pasang aplikasi Github di akun atau organisasimu, kemudian pilih repositori kode bot kamu berada.
Nice!

2022-07-31 07:38 UTC, fadzikri approved these changes
Ok. Good.

2022-08-19 05:37 UTC, merged