[Translations] [Indonesian]: /Id/advanced/deployment.md
CikiMomogi-grammY/website pull request #9
Opened 2022-05-21 11:00 UTC by CikiMomogi

To do:
- [ ] Fix the anchor links

2022-05-31 02:15 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +4. **Opsional.** Gunakan [plugin `auto-retry`](../plugins/auto-retry.md) untuk menangani error `flood wait` secara otomatis.
- [ ] Fix these anchor links

2022-05-31 02:15 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +2. [Gunakan `sequentialize` dengan _session key_ dari _resolver function_ yang sama sebagai _session middleware_ kamu](./scaling.md#concurrency-itu-sulit),
- [ ] Fix anchor link

2022-05-31 02:15 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +4. Implementasikan [graceful shutdown](./reliability.md#graceful-shutdown) ketika hendak menghentikan bot (misalnya untuk beralih ke versi baru).
- [ ] Fix anchor link

2022-05-31 02:15 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +   [Hal ini akan mengakibatkan error timeout](../guide/deployment-types.md#ending-webhook-requests-in-time) pada webhooks, dan pemrosesan update berulang kali dikarenakan Telegram akan terus mengirim
- [ ] Fix anchor link

2022-05-31 02:15 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +3. Jika mengatur opsi `getSessionKey` untuk session, [Gunakan `sequentialize` dengan _session key_ dari _resolver function_ yang sama sebagai _session middleware_ kamu.](./scaling.md#concurrency-itu-
- [ ] Fix anchor link

2022-05-31 02:15 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +5. Pertimbangkan untuk menggunakan [webhook reply](../guide/deployment-types.md#webhook-reply).
- [ ] Fix anchor link

2022-05-31 02:15 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +1. Pertimbangkan menggunakan `lazySessions` seperti yang sudah dijelaskan [di sini](../plugins/session.md#lazy-sessions).
- [ ] Fix anchor link

2022-08-07 13:09 UTC, fadzikri requested changes
Itu saja sih.

2022-08-07 13:09 UTC, fadzikri commented on site/docs/id/advanced/deployment.md
> +1. [Gunakan grammY runner.](../plugins/runner.md).
```suggestion
1. [Gunakan grammY runner](../plugins/runner.md).
```

2022-08-07 13:09 UTC, fadzikri commented on site/docs/id/advanced/deployment.md
> +1. [Gunakan grammY runner.](../plugins/runner.md).
Titiknya ikutan jadi link dan itupun jadi ada 2

2022-08-07 13:09 UTC, fadzikri approved these changes

2022-08-07 13:57 UTC, CikiMomogi commented on site/docs/id/advanced/deployment.md
> +1. [Gunakan grammY runner.](../plugins/runner.md).
Typo. Good catch!

2022-08-19 03:56 UTC, merged